// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231116073520_AddedNotes")]
    partial class AddedNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChapterApp.Models.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.HasKey("ChapterId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("ChapterApp.Models.ChapterLink", b =>
                {
                    b.Property<int>("LinkId")
                        .HasColumnType("int");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.HasKey("LinkId");

                    b.HasIndex("ChapterId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("ChapterApp.Models.Chapter", b =>
                {
                    b.OwnsOne("ChapterApp.Models.ChapterNote", "Note", b1 =>
                        {
                            b1.Property<int>("ChapterId")
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.HasKey("ChapterId");

                            b1.ToTable("Chapters");

                            b1.WithOwner()
                                .HasForeignKey("ChapterId");
                        });

                    b.Navigation("Note")
                        .IsRequired();
                });

            modelBuilder.Entity("ChapterApp.Models.ChapterLink", b =>
                {
                    b.HasOne("ChapterApp.Models.Chapter", null)
                        .WithMany("Links")
                        .HasForeignKey("ChapterId");
                });

            modelBuilder.Entity("ChapterApp.Models.Chapter", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
